{
    "openapi": "3.0.0",
    "info": {
      "title": "API Ferramenta de Projeto",
      "description": "Ferramentas para projetos, como: catalogação de projetos e controle de tarefas.",
      "termsOfService": "https://api-thesis-track.vercel.app/terms",
      "contact": {
        "email": "gustavobn509@gmail.com"
      },
      "version": "1.0.0"
    },
    "servers": [
        {
          "url": "http://localhost:3000",
          "description": "Servidor Local"
        },
        {
          "url": "https://api-thesis-track.vercel.app/",
          "description": "API no ar"
        }
      ],
    "paths": {
      "/user": {
        "post": {
          "summary": "Obtém informações do usuário",
          "tags": ["Usuários"],
          "responses": {
            "200": {
              "description": "Informações do usuário obtidas com sucesso"
            }
          }
        }
      },
      "/user/login": {
        "post": {
          "summary": "Realiza o login do usuário",
          "tags": ["Usuários"],
          "requestBody": {
            "required": true,
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Usuario"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Login realizado com sucesso",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "properties": {
                      "auth": {
                        "type": "boolean",
                        "description": "Indica se a autenticação foi bem-sucedida"
                      },
                      "token": {
                        "type": "string",
                        "description": "Token de autenticação JWT"
                      },
                      "user": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer",
                            "description": "ID do usuário"
                          },
                          "nome": {
                            "type": "string",
                            "description": "Nome do usuário"
                          },
                          "email": {
                            "type": "string",
                            "description": "Endereço de e-mail do usuário"
                          },
                          "professor": {
                            "type": "integer",
                            "description": "Indica se o usuário é um professor (0 para não, 1 para sim)"
                          },
                          "admin": {
                            "type": "integer",
                            "description": "Indica se o usuário é um administrador (0 para não, 1 para sim)"
                          },
                          "perfil": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "description": "Perfis do usuário"
                            },
                            "description": "Lista de perfis do usuário"
                          }
                        },
                        "description": "Detalhes do usuário"
                      }
                    },
                    "example": {
                      "auth": true,
                      "token": "seu-token-jwt-aqui",
                      "user": {
                        "id": 6,
                        "nome": "Seu nome aqui :)",
                        "email": "alguem-denãoseiquem@educar.rs.gov.br",
                        "professor": 0,
                        "admin": 0,
                        "perfil": []
                      }
                    }
                  }
                }
              }
            }
          }          
        }
      },
      "/user/reset-password/request": {
        "post": {
          "summary": "Solicitar um código de verificação por e-mail",
          "tags": ["Usuários"],
          "requestBody": {
            "required": true,
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "email": {
                      "type": "string",
                      "description": "Endereço de e-mail do usuário"
                    }
                  },
                  "required": ["email"]
                },
                "example": {
                  "email": "reginaldo-bt@educar.rs.gov.br"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Código de verificação enviado com sucesso"
            }
          }
        }
      },
      "/user/update-profile": {
        "put": {
          "summary": "Atualizar o perfil do usuário (nome, email ou senha)",
          "tags": ["Usuários"],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "requestBody": {
            "required": true,
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "email": {
                      "type": "string",
                      "description": "Endereço de e-mail do usuário"
                    },
                    "novaSenha": {
                      "type": "string",
                      "description": "Nova senha do usuário"
                    },
                    "confirmSenha": {
                      "type": "string",
                      "description": "Confirmação da nova senha"
                    },
                    "newEmail": {
                      "type": "string",
                      "description": "Novo endereço de e-mail do usuário"
                    },
                    "newNome": {
                      "type": "string",
                      "description": "Novo nome do usuário"
                    },
                    "codigo": {
                      "type": "string",
                      "description": "Código de verificação enviado por e-mail"
                    },
                    "updateType": {
                      "type": "string",
                      "description": "Tipo de atualização (senha, email, nome, etc.)"
                    }
                  },
                  "required": ["email", "novaSenha", "confirmSenha", "newEmail", "newNome", "codigo", "updateType"]
                },
                "example": {
                  "email": "fgdfs-adsilva26@educar.rs.gov.br",
                  "novaSenha": "1234",
                  "confirmSenha": "1234",
                  "newEmail": "gusfssdftavo-adsilva26@educar.rs.gov.br",
                  "newNome": "Meliça",
                  "codigo": "043100",
                  "updateType": "senha"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Perfil do usuário atualizado com sucesso"
            }
          }
        }
      },      
      
      "/projeto/listar": {
        "get": {
          "summary": "Listar todos os projetos",
          "tags": ["Projetos"],
          "responses": {
            "200": {
              "description": "Lista de projetos obtida com sucesso",
              "content": {
                "application/json": {
                  "example": {
                    "status": 200,
                    "msg": "Lista de Projeto",
                    "resp": [
                      {
                        "id_projeto": 7,
                        "titulo": "Como prevenir uma revolta em um período de guerra",
                        "tema": "guerra",
                        "delimitacao": "guerra e como afeta o desenvolvimento humano",
                        "resumo": "ggjç v çfg çl gf jçxg arg zfgf j afgkf ",
                        "problema": "falta de empatia",
                        "alunos": [
                          {
                            "id_aluno": 7,
                            "nome": "Marlon"
                          },
                          {
                            "id_aluno": 34,
                            "nome": "Malaquias"
                          }
                        ],
                        "professores": [
                          {
                            "id_professor": 51,
                            "funcao": "orientador"
                          }
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      
      "/projeto/listar/{id}": {
        "get": {
          "summary": "Listar um projeto por ID",
          "tags": ["Projetos"],
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "required": true,
              "schema": {
                "type": "integer"
              },
              "description": "ID do projeto a ser listado"
            }
          ],
          "responses": {
            "200": {
              "description": "Projeto encontrado com sucesso",
              "content": {
                "application/json": {
                  "example": {
                    "status": 200,
                    "msg": "Lista de Projeto",
                    "resp": {
                      "id_projeto": 7,
                      "titulo": "Como prevenir uma revolta em um período de guerra",
                      "tema": "guerra",
                      "delimitacao": "guerra e como afeta o desenvolvimento humano",
                      "resumo": "ggjç v çfg çl gf jçxg arg zfgf j afgkf ",
                      "problema": "falta de empatia",
                      "alunos": [
                        {
                          "id_aluno": 7,
                          "nome": "Marlon"
                        },
                        {
                          "id_aluno": 34,
                          "nome": "Malaquias"
                        }
                      ],
                      "professores": [
                        {
                          "id_professor": 51,
                          "funcao": "orientador"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      
      "/projeto/listar/{projetoId}/pessoa/{id}": {
        "get": {
          "summary": "Listar um projeto por ID referenciando seus relacionados",
          "tags": ["Projetos"],
          "parameters": [
            {
              "name": "projetoId",
              "in": "path",
              "required": true,
              "schema": {
                "type": "integer"
              },
              "description": "ID do projeto"
            },
            {
              "name": "id",
              "in": "path",
              "required": true,
              "schema": {
                "type": "integer"
              },
              "description": "ID da pessoa relacionada ao projeto"
            }
          ],
          "responses": {
            "200": {
              "description": "Projeto encontrado com sucesso, referenciando seus relacionados",
              "content": {
                "application/json": {
                  "example": {
                    "status": 200,
                    "msg": "Lista de Projeto Pessoa relacionada",
                    "resp": {
                      "id_projeto": 7,
                      "titulo": "Como prevenir uma revolta em um período de guerra",
                      "tema": "guerra",
                      "delimitacao": "guerra e como afeta o desenvolvimento humano",
                      "resumo": "ggjç v çfg çl gf jçxg arg zfgf j afgkf ",
                      "problema": "falta de empatia",
                      "alunos": [
                        {
                          "id_aluno": 7,
                          "nome": "Marlon"
                        },
                        {
                          "id_aluno": 34,
                          "nome": "Malaquias"
                        }
                      ],
                      "professores": [
                        {
                          "id_professor": 51,
                          "funcao": "orientador"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      
      "/projeto/lista/aluno/curso/{id}": {
        "get": {
          "summary": "Listar projetos de alunos com base no curso",
          "tags": ["Projetos"],
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "required": true,
              "schema": {
                "type": "integer"
              },
              "description": "ID do curso"
            }
          ],
          "responses": {
            "200": {
              "description": "Projeto encontrado com sucesso, referenciando seus relacionados",
              "content": {
                "application/json": {
                  "example": {
                    "status": 200,
                    "msg": "Lista de Projeto Curso específico",
                    "resp": {
                      "id_projeto": 7,
                      "titulo": "Como prevenir uma revolta em um período de guerra",
                      "tema": "guerra",
                      "delimitacao": "guerra e como afeta o desenvolvimento humano",
                      "resumo": "ggjç v çfg çl gf jçxg arg zfgf j afgkf ",
                      "problema": "falta de empatia",
                      "alunos": [
                        {
                          "id_aluno": 7,
                          "nome": "Marlon"
                        },
                        {
                          "id_aluno": 34,
                          "nome": "Malaquias"
                        }
                      ],
                      "professores": [
                        {
                          "id_professor": 51,
                          "funcao": "orientador"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/buscar-projetos": {
        "get": {
          "summary": "Buscar projetos pelo título",
          "tags": ["Projetos"],
          "responses": {
            "200": {
              "description": "Projetos encontrados com sucesso"
            }
          }
        }
      },
      
      "/buscar-projetos/ano": {
        "get": {
          "summary": "Buscar projetos públicos por ano",
          "tags": ["Projetos"],
          "responses": {
            "200": {
              "description": "Projetos encontrados com sucesso"
            }
          }
        }
      },
      
      "/projeto/adiciona": {
        "post": {
          "summary": "Criar um novo projeto",
          "tags": ["Projetos"],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "requestBody": {
            "required": true,
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Projeto"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Projeto criado com sucesso"
            }
          }
        }
      },
      
      "/projeto/atualiza/{id}": {
        "put": {
          "summary": "Atualizar um projeto por ID",
          "tags": ["Projetos"],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "required": true,
              "schema": {
                "type": "integer"
              },
              "description": "ID do projeto a ser atualizado"
            }
          ],
          "responses": {
            "200": {
              "description": "Projeto atualizado com sucesso"
            }
          }
        }
      },
      
      "/projeto/delete/{id}": {
        "delete": {
          "summary": "Deletar um projeto por ID",
          "tags": ["Projetos"],
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "required": true,
              "schema": {
                "type": "integer"
              },
              "description": "ID do projeto a ser deletado"
            }
          ],
          "responses": {
            "200": {
              "description": "Projeto deletado com sucesso"
            }
          }
        }
      }
    },
    "components": {
        "schemas": {
          "Usuario": {
            "type": "object",
            "properties": {
              "id_pessoa": {
                "type": "integer",
                "description": "ID do usuário"
              },
              "nome": {
                "type": "string",
                "description": "Nome do usuário"
              },
              "email": {
                "type": "string",
                "description": "Endereço de e-mail do usuário"
              }
            }
          },
          "Projeto": {
            "type": "object",
            "properties": {
              "id_projeto": {
                "type": "integer",
                "description": "ID do projeto"
              },
              "titulo": {
                "type": "string",
                "description": "Título do projeto"
              },
              "resumo": {
                "type": "string",
                "description": "Resumo do projeto (até 300 caracteres)"
              },
              "abstract": {
                "type": "string",
                "description": "Abstract do projeto (até 300 caracteres)"
              },
              "problema": {
                "type": "string",
                "description": "Descrição do problema (até 250 caracteres)"
              },
              "tema": {
                "type": "string",
                "description": "Tema do projeto"
              },
              "delimitacao": {
                "type": "string",
                "description": "Delimitação do projeto"
              },
              "arquivo": {
                "type": "string",
                "format": "binary",
                "description": "Arquivo do projeto (BLOB)"
              }
            }
          }
        }
      }      
  }